map_type: costmap

obstacle_range: 3 #was 2.5. 5 was bad
#5 can  sudenly make an obstacle far away and never revisit it.
raytrace_range: 3.0

transform_tolerance: 0.3

robot_radius: 0.3  #0.3 works
inflation_radius: 0.55 ##0.55 works

observation_sources: laser_scan_sensor

#laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, #marking: true, clearing: true}
laser_scan_sensor: {sensor_frame: camera_rgb_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
